  language: python
  python:
    - "2.7"
    - "3.5"
    - "3.6"

  sudo: required

  cache: pip

  addons:
    apt:
      packages:
        libjs-mathjax

  script:
    - pip install -U .[test,doc]
    - python setup.py test
    - cd doc; make html; cd ..

  deploy:
    provider: pypi
    user: scottgigante
    password: ${PYPI_PASSWORD}
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      branch: master

  after_success:
    - coveralls
