  language: python
  python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

  sudo: required

  cache:
    - pip
    - apt

  addons:
    apt:
      packages:
        libjs-mathjax

  script:
    - pip install -U .[test]
    - if [ "$TRAVIS_PYTHON_VERSION" != "3.5" ]; then black . --check --diff; fi
    - python setup.py test
    - pip install -U .[doc]
    - cd doc; make html
    - cd ..

  deploy:
    provider: pypi
    user: scottgigante
    password: ${PYPI_PASSWORD}
    distributions: sdist bdist_wheel
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      branch: master

  after_success:
    - coveralls
